FROM node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

COPY pnpm-lock.yaml package.json ./
RUN pnpm install --frozen-lockfile

COPY . .

ENV  NODE_ENV=development
ENV  PORT=4000

CMD ["pnpm", "dev"]